# Shared FNO model configuration
# Interpolates ALL parameters from system_params
name: "${system_params.name}_fno"
dropout: ${system_params.fno_dropout}
hidden_channels: ${system_params.fno_hidden_channels}
encoder_layers: ${system_params.fno_encoder_layers}
downsampler_layers: ${system_params.fno_downsampler_layers}
mlp_layers: ${system_params.fno_mlp_layers}
use_partials: True
model_config:
  _target_: pdeinvbench.models.inverse_model.InverseModel
  paramnet: 
    _target_: pdeinvbench.models.inverse_model.ParameterNet
    pde: ${data.pde}
    normalize: ${system_params.normalize}
    logspace: ${system_params.logspace}
    params_to_predict: ${system_params.params_to_predict}
    mlp_type: ${system_params.mlp_type}
    encoder:
      _target_: pdeinvbench.models.encoder.FNOEncoder
      n_modes: ${system_params.fno_n_modes}
      n_past: ${n_past}
      n_future: ${n_future}
      n_layers: ${model.encoder_layers}
      data_channels: ${data.num_channels}
      hidden_channels: ${model.hidden_channels}
      use_partials: ${model.use_partials}
      pde: ${data.pde}
      batch_size: ${data.batch_size}
    downsampler: ${system_params.fno_downsampler}
    mlp_hidden_size: ${model.hidden_channels}
    mlp_layers: ${model.mlp_layers}
    mlp_activation: "relu"
    mlp_dropout: ${model.dropout}
    downsample_factor: ${data.downsample_factor}

